### PR TITLE
Update README.md with contributor avatar pictures

### PR DESCRIPTION
**Pull request by seancyw**

### CODE REVIEW

**Comment by ows-ali** [comment]
Great work. Is it possible to have 3 or 4 people in one row? There is a lot of empty space and README file looks way too lengthy.

**Comment by m-sameer** [comment]
@seancyw You may place the images right next to their names like line 47 should be on line 35. Ask for clarification if you didn't understand the idea.

**Comment by seancyw** [comment]
@ows-ali ,
I have changed accordingly which looks much better to combine the image together with the contributors table instead of having a standalone table for it.
Thanks for your suggestion @m-sameer .

**Comment by m-sameer** [comment]
@seancyw Now it's way better.

**Comment by ows-ali** [comment]
Great work guys! Looks much better. Thanks @seancyw and @m-sameer. Fixes #16

**Pull request merged**
