### PR TITLE
Fix CONTRIBUTING.md redirection

### PR DESCRIPTION
**Pull request by ouassimBenMosbah**
The redirection was broken

### CODE REVIEW

**Comment by ows-ali** [comment]
Please add your name and info in README.md and push one more commit

**Comment by ouassimBenMosbah** [comment]
> Please add your name and info in README.md and push one more commit

Done

**Comment by ows-ali** [comment]
Oh I am sorry I had to revert your PR because the README file was not updated. 
So please pull the changes (see upstream) and then make pull request again to add your name in contributors. 
(Do not need to change the links because it is already noticed by others because of you :) so just add your name in contributors in README)

**Comment by ows-ali** [comment]
@ouassimBenMosbah

**Comment by ouassimBenMosbah** [comment]
In wich branch should I do it please ?

**Comment by ows-ali** [comment]
Pull the code from this repo (you can see about upstream in README.md) and then add your name/info and push to ouassimBenMosbah:Fix-contributing branch @ouassimBenMosbah

**Comment by ouassimBenMosbah** [comment]
Here you go: https://github.com/ows-ali/Hacktoberfest/pull/91

Is it good ?

**Comment by ows-ali** [comment]
> Here you go: #91
> 
> Is it good ?

@ouassimBenMosbah Yes Perfect!

**Pull request merged**
