### PR TITLE
Added FLOW008.py

### PR DESCRIPTION
**Pull request by tramgolam**
Codechef problem Servant:
https://www.codechef.com/problems/FLOW008

###### Closing Issue/Referencing Issue
issue reference (#) 

###### Changes Made In Pull Request

*
*

### CODE REVIEW

**Comment by ows-ali** [comment]
@tramgolam Please add your name and info in README and push again

**Comment by tramgolam** [comment]
I added my information to the readme during a previous OR.

-Tiffany

**Comment by ows-ali** [comment]
There are #165 and #166 PRs. But these PRs do not have README changes. Please make a new branch and PR or just push to tramgolam-new branch

**Comment by tramgolam** [comment]
Ah I understand now. I'll push an updated readme. Thanks

**Comment by ows-ali** [comment]
Sure, Looking forward for it.

**Comment by ows-ali** [comment]
@tramgolam Please make a new PR after adding name/info in README. So, that you may get a partial credit for merged request, if there is any, for Hacktoberfest

**Pull request merged**
