### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by rmoswela**
added a PR template in the root directory

### CODE REVIEW

**Comment by ows-ali** [comment]
Hey I don't think we need 'reviewed by' and also can you change 'Closing Issue' to 'Closing Issue/Referencing Issue'?

**Comment by rmoswela** [comment]
Awesome i fixed as per your recommendation. Any bugs one might try? this is really awesome

**Comment by ows-ali** [comment]
I have merged the template so that people can start using it, you can add more make changes by making an issue and then adding a PR.
Thanks a lot for the template @rmoswela

**Comment by ows-ali** [comment]
Closes #56

**Pull request merged**
