### PR TITLE
Customize welcome bot

### PR DESCRIPTION
**Pull request by brianabaker**
###### Closing Issue/Referencing Issue
issue reference (#59) 

###### Changes Made In Pull Request

* customized the welcome bot

### CODE REVIEW

**Comment by ows-ali** [comment]
Hey @brianabaker can you please add the upstream and take the updated version of this repo, then push to your forked branch.
Also can you please edit 'newPRWelcomeComment'? It is showing non Github-Markdown supported characters

**Comment by brianabaker** [comment]
Fixed newPRWelcomeComment and synced my repo with upstream.

**Comment by ows-ali** [comment]
Thanks a lot. It looks great now.

**Comment by ows-ali** [comment]
https://github.com/ows-ali/Hacktoberfest/pull/99
Good work :)

**Pull request merged**
