### PR TITLE
Added stdin and stdout 1 challenge solution.

### PR DESCRIPTION
**Pull request by oskarikotajarvi**
###### Closing Issue/Referencing Issue
issue reference (#1) 

###### Changes Made In Pull Request

*
*

### CODE REVIEW

**Comment by ows-ali** [comment]
@oskarikotajarvi 
- Please remove .project file or add an issue first
- Please add your name/info in README.md and push again

**Comment by oskarikotajarvi** [comment]
@ows-ali 
I'm quite new to this. How should i go about to remove the .project file from the PR?

**Comment by oskarikotajarvi** [comment]
@ows-ali  .project file has now been remover from the PR

**Comment by ows-ali** [comment]
@oskarikotajarvi Awesome job!

**Pull request merged**
