### PR TITLE
Frecodecamp first problem

### PR DESCRIPTION
**Pull request by Avinash369**
First Freecodecamp problem

### CODE REVIEW

**Comment by ows-ali** [comment]
Add your name and info in Contributors list in README

**Comment by Avinash369** [comment]
https://learn.freecodecamp.org/coding-interview-prep_project-euler_problem-1-multiples-of-3-and-5.js

Is this url ok?

**Comment by Avinash369** [comment]
I have proposed a change in Readme for contributors. Is it ok or do i have to change on my local machine and then push it to the repo

**Comment by ows-ali** [comment]
Yes @Avinash369 use this name 'coding-interview-prep_project-euler_problem-1-multiples-of-3-and-5.json' as the name of the file. 
Also, yes you need to push the updated README.md and push it to your forked repo (Avinash369:master). It will automatically come here

**Comment by Avinash369** [comment]
changed the file name and also updated the README.md 
check if anything else is needed

**Comment by ows-ali** [comment]
Thanks @Avinash369 for choosing the theme. It looks nice and now working on https://ows-ali.github.io/Hacktoberfest

**Pull request merged**
