### PR TITLE
Added "word order" challenge from hackerrank

### PR DESCRIPTION
**Pull request by dhiegomaga**
###### Changes Made In Pull Request

* Added [__word order challenge__](https://www.hackerrank.com/challenges/word-order/problem) from hackerrank

### CODE REVIEW

**Comment by ows-ali** [comment]
Do not edit CONTRIBUTING.md in the same PR. I have received your PR for this. Please update your word_order_branch and leave the CONTRIBUTING.md as is. Thanks @dhiegomaga

**Comment by dhiegomaga** [comment]
yeah, I realized this later! I’ll fix it haha

**Comment by sunnycal** [comment]
Hi all i just want to start as a first timer and i am just wondering how to dig in and start contributing with any first time projects? is there a chat room for this?

**Comment by sunnycal** [comment]
@ows-ali hi there. i just started following and i listed a couple comments. can you reply with steps i should take to start contributing?

**Pull request merged**
