### PR TITLE
Added Issue Creation template

### PR DESCRIPTION
**Pull request by seancyw**
###### Closing Issue/Referencing Issue
issue reference (#) #55 

###### Changes Made In Pull Request
* Added Issue Creation template
*

### CODE REVIEW

**Comment by ows-ali** [comment]
@seancyw Do you require file for Udemy in this PR?

**Comment by seancyw** [comment]
@ows-ali ,
Sorry, it was seen as part of this PR as I was using the same repo for creating the templates. The issue is fixed now after merging with the upstream master branch. Thanks 👍

**Comment by ows-ali** [comment]
@seancyw Great!

**Comment by ows-ali** [comment]
Close #55

**Pull request merged**
