### PR TITLE
Added Udacity Android Basics Nanodegree Course Project

### PR DESCRIPTION
**Pull request by sinhaDroid**
Hello @ows-ali,

I have one of the projects of android basics nano degree course of udacity. Hope, this will help.

### CODE REVIEW

**Comment by ows-ali** [comment]
@sinhaDroid Please change the files as according to the CONTRIBUTING.md and add your name/info in README.md

**Comment by sinhaDroid** [comment]
@ows-ali,

There is no udacity folder, please suggest where to upload.

**Comment by ows-ali** [comment]
You can make a new folder and file in your local, and then push it

**Comment by sinhaDroid** [comment]
Exactly, I did the same. Please check

**Comment by sinhaDroid** [comment]
Hello @ows-ali,

I fixed the issue, Please check.

**Comment by ows-ali** [comment]
It is a single project PR, so we can merge it.

**Pull request merged**
